import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/reusables/header";
import { GeistSans } from 'geist/font/sans';
import { Montserrat } from "next/font/google";
import Script from "next/script";
import Footer from "@/components/reusables/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',  // <--------- 👈
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
      <Script
        id="custom-config"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: `var zkRjY_rDG_qcNNuc={"it":4434283,"key":"82674"};`,
        }}
      />
      <Script
        src="https://dq3fmbwarp7li.cloudfront.net/6695631.js"
        strategy="afterInteractive"
        async
      />
      </head>
      <body
         className={`${montserrat.variable} antialiased`}
      >
        <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
